### ISSUE TITLE
Crash when creating a new freeplay save with DEV_ACTIVE and a few other mods

### ISSUE THREAD

**Issue by SunSerega** [ClaudeMetz/FactoryPlanner#365] opened 2024-10-24 22:12 UTC
### Problem Description

Minimal mod list:
```
base
factoryplanner
flib
GhostWarnings
ModuleInserterSimplified
```
The problem is that when `DEV_ACTIVE` is set, this mod tries to immediately unlock all tech in `player_init`.
And `ModuleInserterSimplified` has an `on_research_finished` handler, which calls this:
```
function Config.process_technology(technology, player_index, old_modules_enabled)
  old_modules_enabled = old_modules_enabled or {}
  local player_data = storage.player_data[player_index]
  local modules_enabled = player_data.modules_enabled
  ...
```
But `storage.player_data` is not populated yet, probably because `on_player_created` is still being handled by `factoryplanner`, so `ModuleInserterSimplified`'s handler for the same event hasn't executed yet.
So `player_data` is set to `nil`, and this crashes on the next line.

Not sure what mod should fix it, or if this is even considered an issue here, but this is a bit annoying for development...

### Reproduction

1. Launch the game with those mods and with the dev version of this mod.
2. Create a new freeplay save with default parameters.
3. Crash when it loads.

**Comment by ClaudeMetz** [comment] 2024-10-27 14:34
Hello, this is a weird configuration you got there. That error is the other mod's fault, not mine. The events thing you describe isn't really how this works. I also don't suggest using FP with devmode on, it's not intended to be stable. So I'll close this as not a bug, sorry :)

**Closed by ClaudeMetz** 2024-10-27 14:34 UTC
Labels: bug

**Comment by SunSerega** [comment] 2024-10-27 16:09
Can you please explain what doesn't work how I described? I do see that the other mod can just set it's event later (and handle existing tech right before that), but you make it sound like my misunderstanding is more fundamental.

**Comment by ClaudeMetz** [comment] 2024-10-27 16:44
`storage` is specific to each mod, so if that mod's storage is empty, it's because it hasn't filled it yet. My mod can't influence that in any way.

Although I re-read your message, and you are right about the event order issue I think. Still, not something I can do anything about unfortunately.
