### ISSUE TITLE
Crash loading a save game after most recent update

### ISSUE THREAD

**Issue by pepoluan** [ClaudeMetz/FactoryPlanner#432] opened 2024-11-26 16:52 UTC
### Problem Description

I just updated the mod to version 2.0.15, and now Factorio crashes on loading a save game.

Here's the error message:

```
The mod Factory Planner (2.0.15) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_configuration_changed
__factoryplanner__/backend/handlers/generator.lua:1041: attempt to compare number with nil
stack traceback:
	__factoryplanner__/backend/handlers/generator.lua:1041: in function <__factoryplanner__/backend/handlers/generator.lua:1040>
	[C]: in function 'sort'
	__factoryplanner__/backend/handlers/prototyper.lua:65: in function 'apply'
	__factoryplanner__/backend/handlers/prototyper.lua:86: in function 'convert_and_sort'
	__factoryplanner__/backend/handlers/prototyper.lua:115: in function 'build'
	__factoryplanner__/backend/init.lua:244: in function <__factoryplanner__/backend/init.lua:229>
```

Requested attachments:
* [factorio-current.log](https://github.com/user-attachments/files/17922897/factorio-current.log)
* The save file that cannot be loaded: [13-43.zip](https://github.com/user-attachments/files/17922911/13-43.zip)

### Reproduction

1. Upgrade mod from prior version to 2.0.15
2. Open a save file

**Comment by ClaudeMetz** [comment] 2024-11-26 16:58
Thanks for the report! This is actually a duplicate of #428, fix is out very soon.

**Closed by ClaudeMetz** 2024-11-26 16:58 UTC
Labels: bug
