### ISSUE TITLE
Non-Recoverable Error On Toggle Belt/Lane Switch

### ISSUE THREAD

**Issue by iceblade92** [ClaudeMetz/FactoryPlanner#274] opened 2024-03-18 17:52 UTC
### Problem Description

i got a tone of mods so no cule if its my fault but what happend was i opend the planer for the first time and saw a setting for prefferances to look around a bit and found the switch that sais belt and lanes so i fought i would click it to see what it is but this is the moment i got the crash.

The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_switch_state_changed (ID 151)
__factoryplanner__/backend/calculation/solver.lua:181: attempt to index local 'factory' (a nil value)
stack traceback:
	__factoryplanner__/backend/calculation/solver.lua:181: in function 'update'
	__factoryplanner__/ui/dialogs/preferences_dialog.lua:252: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

### Reproduction

1.have lots of mods
2.open factory planer
3.open prefferances
4.click belt/lane toggle

**Comment by jDomantas** [comment] 2024-10-03 19:29
Got the same crash with minimal mods:

* Factorio 1.1.110
* Factory planner 1.1.79
* Factorio library 0.14.1

In a new game, open factory planner, open preferences, click belt/lane toggle, crash.

**Comment by ClaudeMetz** [comment] 2024-10-13 09:29
Hello, this is a dupe of #245, which also happens to be fixed for 2.0 :)

**Closed by ClaudeMetz** 2024-10-13 09:29 UTC
Labels: bug
