### ISSUE TITLE
Crash when removing productivity modules from a line item

### ISSUE THREAD

**Issue by mheidal** [ClaudeMetz/FactoryPlanner#119] opened 2023-08-23 03:14 UTC
I got a crash when using factory planner. The crash occurred when ctrl-right clicking on the productivity modules in a subfactory which had no line items except the "Vulcanite Enrichment" recipe. The crash occurred in a multiplayer game with a bunch of QOL mods which shouldn't interact with Factory Planner as well as Space Exploration and its requirements. The recipe is from Space Exploration.

Crash report:
```
The mod Factory Planner (1.1.72) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/backend/classes/Collection.lua:57: Can't remove nil dataset
stack traceback:
    [C]: in function 'error'
    __factoryplanner__/backend/classes/Collection.lua:57: in function 'remove'
    __factoryplanner__/backend/classes/ModuleSet.lua:36: in function 'remove'
    __factoryplanner__/ui/main/production_handler.lua:203: in function 'handler'
    __factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
```

Subfactory string: `eNq9Vttu3DYQ/RVDz5Wqy14N9KFuE6CAAxjeIH0IAoGiZleMKVIlKcPuwv+eGZLa7PoaBEXzlJ0Zzpw5c2bkfdLrtr4FY4VWyXlSZEW2LJNfErgbtHE1ei245HyfNMxCDFitMeD979eX6VbcQZt6xwwdFdqt6DuQA5gYPEPbJ+gEl7BRbAjWVTZH89/CwKbDMnx0NoYXlIMxkXKtHBMKkaEnz8qsKKLHip1iMnWGKdsLG5Hn2SxbUYQUoNJG6B7Cy4U3wy1aW2GdEc3opmbzrMipF8adNvcbYIZ3AUgekGylaHyWosyo651hwyCF2qW7MVStfNdCbbXpmTN6slLfX8ENjN9Ei094qXcIQvBr+GcE6z4wxXYHrioC80G3o4S/lAXjwGxEj/W2AtojPpW4E5C6sYGJNko9jLbD3txhkESY0Y12NXPYt5uImmcF0W87AbJNB6O/AvUf+swW5NKSmZQzySfslMtiM5CiMqQ2jLKlRAeOdiI6pH0xKi2nuNfDqhhWvh42+7Gw+atFe1AjKqofpf99LJnNIFqcAY70neqY4oCxUaerrFhSBM6Q3Zx97Iwed130eDiuDcIpoiod3LkBSxw06XVHahaqHVGV93EypZeAkKgNreJ4kX7S3pXgN2D+1BIVHhylH9aVGOCTsCMq/98opdw7roGj60JrUmCFyWk8H9kAKGBa2RLj1t5kby5RlXGL6Ok2bARCVuogz+WzTE8NFaFx1Dvubt8IxYKmirgiT7kftHWoPg52YqWk2hfaOQkKOIJyEBtdJg+YYmwCME/A532iWE8Bn0W/+w1j+18tpLej5EzhrxSUEbyD9svZu/i/s4OTZiLwRKDGMcMix6XSYTroaeQIgxF+2nuse2VwJ7k/g7qhZQnVEbvTZIwwLFMtvuY45p32EyVMaGmZY7W7HyCabLiTh8V2ZgQsw3o9KqxS4triecDr2NaTbZ+0sMWxtXVDiaP55E0D0tUR05ZJSymdHmqJt0+GIghOMs/21NLDl++2P1Ba2BzNFJ/SNRN39dYA1AG054IybqWm0e6TSy+kU1ambN5HnZAIKegJXc/N6hFb4fULfA2hB8Q7hQcLlZ1QhB2gflA44hYmHlpNyD1NmAgMx93GS5ycF3lOvfMutvYYNQUasR13cDrqgx0/Do+aiNle6AI/HBxqKXrhJnC9/wTU8csbftm31DexcSvcfRrepNUpxuOQxxhjkbeEOfEavlKvyOc0cIOtHBsjvw+kWsbpiDxtKHpOcQbjGziLn6TQDoB/zjzPnff9DGmr/4q0i8DH/3+Pimx9+m9VltViVhWLfL5eL2freTWvyrJYrauqyOezxWo5Pzk9cc1+9Pa8zE/MV3z3v/en6IilzfSNuMf8D98AY2mKxg==`

**Comment by ClaudeMetz** [comment] 2023-08-25 13:58
Unfortunately, I can't reproduce this from the export string. It seems like the issue is that your data structure got screwed up somehow, which is masked/fixed by the import/export process. So I could try and figure it out with a provided save, but I'll say you can hold off on that for a bit, since there is a rewrite coming that will make this code obsolete anyways.

**Comment by ellisonch** [comment] 2023-09-21 01:19
FWIW, I'm getting an identical crash while playing Nullius.  I did the same thing to trigger it; ctrl-right clicking a module in a machine to remove it.

**Comment by ClaudeMetz** [comment] 2023-10-28 17:21
Not sure how to fix this without a repro, open a new issue if you're able to reproduce it!

**Closed by ClaudeMetz** 2023-10-28 17:21 UTC
Labels: bug
