### ISSUE TITLE
Crash when changing UI scale or on loading Save with different UI scaling "on_player_display_scale_changed"

### ISSUE THREAD

**Issue by hjtroteclaser** [ClaudeMetz/FactoryPlanner#431] opened 2024-11-26 14:44 UTC
### Problem Description

- I tried to load a save with UI scale changed --> crash.
- Then tried setting it back to as when it was saved --> load
- Then changing UI scale when in game --> crash

![image](https://github.com/user-attachments/assets/eb4fb69f-5802-499b-b092-013818f972f4)

### initial bug
1. Windows PC: UI Scale set to 125%
2. Factorio: Set UI Scale to "Manual points 100%"
![image](https://github.com/user-attachments/assets/eb4fb69f-5802-499b-b092-013818f972f4)
4. Play Factorio with mod and save.
5. Factorio: Set UI Scale to Automatic
6. load game --> crash
``` lua
The mod Factory Planner (2.0.15) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_player_display_scale_changed (ID 107)
__factoryplanner__/ui/components/item_views.lua:239: attempt to index local 'view' (a nil value)
stack traceback:
	__factoryplanner__/ui/components/item_views.lua:239: in function 'func'
	__factoryplanner__/ui/components/item_views.lua:222: in function 'run_on_all_views'
	__factoryplanner__/ui/components/item_views.lua:248: in function 'rebuild_interface'
	__factoryplanner__/ui/base/main_dialog.lua:105: in function 'rebuild'
	__factoryplanner__/ui/base/main_dialog.lua:41: in function 'shrinkwrap_interface'
	__factoryplanner__/ui/base/main_dialog.lua:224: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:330: in function <__factoryplanner__/ui/event_handler.lua:307>
```

### narrowed down bug
UI scale change bug while ingame

1. play game
2. go to interface settings
3. change UI scaling
4. confirm, resume
5. exception:
```lua
The mod Factory Planner (2.0.15) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_player_display_scale_changed (ID 107)
__factoryplanner__/ui/components/item_views.lua:239: attempt to index local 'view' (a nil value)
stack traceback:
	__factoryplanner__/ui/components/item_views.lua:239: in function 'func'
	__factoryplanner__/ui/components/item_views.lua:222: in function 'run_on_all_views'
	__factoryplanner__/ui/components/item_views.lua:248: in function 'rebuild_interface'
	__factoryplanner__/ui/base/main_dialog.lua:105: in function 'rebuild'
	__factoryplanner__/ui/base/main_dialog.lua:41: in function 'shrinkwrap_interface'
	__factoryplanner__/ui/base/main_dialog.lua:224: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:330: in function <__factoryplanner__/ui/event_handler.lua:307>
```

**Comment by hjtroteclaser** [comment] 2024-11-26 16:55
It also crashes when opening FactoryPlanner when in Game.
Downgraded to 2.0.14 and no crashes at all.

**Comment by ClaudeMetz** [comment] 2024-11-26 17:00
Thanks for the very nice and detailed report. This is actually a duplicate of #431 fundamentally, which was just fixed :)

**Closed by ClaudeMetz** 2024-11-26 17:00 UTC
Labels: bug
