### ISSUE TITLE
`production_handler.lua:168: attempt to index field 'parent' (a nil value)`

### ISSUE THREAD

**Issue by Quezler** [ClaudeMetz/FactoryPlanner#246] opened 2024-01-15 20:29 UTC
### Problem Description

15153.400 Error MainLoop.cpp:1391: Exception at tick 42796529: The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/ui/main/≈
stack traceback:
	__factoryplanner__/ui/main/production_handler.lua:168: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
15153.400 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/ui/main/production_handler.lua:168: attempt to index field 'parent' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_handler.lua:168: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>"

### Reproduction

The player on the multiplayer server mentioned modules and possibly rightclick, unfortunately wasn't able to reproduce.

**Comment by ClaudeMetz** [comment] 2024-10-13 09:24
Hello, this seems to be a duplicate of #217, thanks for the report.

**Closed by ClaudeMetz** 2024-10-13 09:24 UTC
Labels: bug
