### ISSUE TITLE
Crash when editing module (can reproduce)

### ISSUE THREAD

**Issue by AlpacaStorm** [ClaudeMetz/FactoryPlanner#263] opened 2024-02-16 16:52 UTC
### Problem Description

The game crashed.
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/44841996/fefaa1ff-a12e-4b02-86d4-2d148e285ad2)

### Reproduction

1.create a recipe and add some module
2.right click on the module(open edit machine gui)
3.right click on the module(remove module in edit machine gui)
4.click cancel(back to main gui, the module icon still remain)
5.right click on the module
6.crash

**Comment by ClaudeMetz** [comment] 2024-10-13 18:12
Duplicate of #263, very helpful reproduction though so thanks!

**Closed by ClaudeMetz** 2024-10-13 18:12 UTC
Labels: bug
