### ISSUE TITLE
Instant crash on game load

### ISSUE THREAD

**Issue by msrd0** [ClaudeMetz/FactoryPlanner#279] opened 2024-03-21 20:44 UTC
### Problem Description

I used to have this old game of mine that I just loaded because I wanted to see how I did a certain design back then. However, the game crashes immediately on load. Disabling this mod fixes the problem.

![Screenshot_2024-03-19-22-54-22](https://github.com/ClaudeMetz/FactoryPlanner/assets/7853372/c7d937b4-50d9-454e-a1c7-dda8f2383f1b)

Savegame: https://gigamove.rwth-aachen.de/en/download/d8e669d6bd089668c11823490fe5f89f (downloadable until 4/4/2024, unfortunately too big to upload to github)

**Comment by ClaudeMetz** [comment] 2024-10-13 18:37
Hmm this is a migration issue caused by moving many versions at once I assume. I could probably prevent it, but since we're all moving to 2.0 soon, it's not really gonna be worth it.

I know this report is ancient, so you likely moved on, but the way to fix this is to load with the old version of the mod, export all your factories into a string, then update the mod and re-import everything there. Anyways, appreciate the report.

**Closed by ClaudeMetz** 2024-10-13 18:37 UTC
Labels: bug
