### ISSUE TITLE
Crash on new savefile

### ISSUE THREAD

**Issue by add-IV** [ClaudeMetz/FactoryPlanner#430] opened 2024-11-26 13:16 UTC
### Problem Description

Crashes even on new savefile

```
The mod Factory Planner (2.0.15) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_init()
__factoryplanner__/backend/handlers/generator.lua:1041: attempt to compare number with nil
stack traceback:
	__factoryplanner__/backend/handlers/generator.lua:1041: in function <__factoryplanner__/backend/handlers/generator.lua:1040>
	[C]: in function 'sort'
	__factoryplanner__/backend/handlers/prototyper.lua:65: in function 'apply'
	__factoryplanner__/backend/handlers/prototyper.lua:86: in function 'convert_and_sort'
	__factoryplanner__/backend/handlers/prototyper.lua:115: in function 'build'
	__factoryplanner__/backend/init.lua:217: in function <__factoryplanner__/backend/init.lua:204>
```

### Reproduction

1. create new save
2. crashes

**Comment by ClaudeMetz** [comment] 2024-11-26 16:45
Thanks for the report, this one is a duplicate of #428

**Closed by ClaudeMetz** 2024-11-26 16:45 UTC
Labels: bug
