### ISSUE TITLE
Crash when deleting subfloor recipe (possible once you delete all subfloor ingredients).

### ISSUE THREAD

**Issue by Kaimdrol** [ClaudeMetz/FactoryPlanner#193] opened 2023-11-26 01:47 UTC
### Problem Description

Factorio 1.1.94, Factory Planner 1.1.75, Factorio Library 0.13.0
No other mod required to crash.

**Deleting all the subfloor ingredients allows you to delete the main subfloor recipe and crash the mod.**

_Screenshots available at https://imgur.com/a/y2Qyu4m
Log included [factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/13465694/factorio-current.log)
Works on a fresh base game, so no savegame included._

### Log file :
```
719.686 Error MainLoop.cpp:1391: Exception at tick 6899: The mod Factory Planner (1.1.75) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 206)
__factoryplanner__/ui/main/production_table.lua:77: attempt to index field 'parent' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_table.lua:77: in function '?'
	__factoryplanner__/ui/main/production_table.lua:434: in function 'render_lines'
	__factoryplanner__/ui/main/production_table.lua:442: in function 'refresh_production_table'
	__factoryplanner__/ui/main/production_table.lua:472: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:308: in function <__factoryplanner__/ui/event_handler.lua:288>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/main/production_handler.lua:60: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/main/production_handler.lua:60: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
 768.534 Quitting: user-quit.
```

### Steps to reproduce :
 - Create a factory with at least one subfloor.
 - The subfloor recipe can't be deleted.
 - Add any number of ingredients to the subfloor
 - Deleting all the subfloor ingredients removes the main recipe protection
 - Delete the subfloor main recipe to crash the planner (return to Factorio main menu).

**Comment by kryojenik** [comment] 2023-11-27 10:21
Possibly a duplicate of #182

**Comment by ClaudeMetz** [comment] 2023-11-27 14:44
Indeed a duplicate, appreciate the very detailed report though Kaimdrol! Further conversation in 182.

**Closed** 2023-11-27 14:45 UTC
Labels: bug
