### ISSUE TITLE
crash when click a recipe

### ISSUE THREAD

**Issue by PlexPt** [ClaudeMetz/FactoryPlanner#395] opened 2024-11-09 09:10 UTC
18784.920 Error MainLoop.cpp:1429: Exception at tick 10488095: The mod Factory Planner (2.0.4) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 246)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	[C]: in function '__index'
	__factoryplanner__/ui/base/modal_dialog.lua:174: in function 'enter'
	__factoryplanner__/ui/event_handler.lua:222: in function <__factoryplanner__/ui/event_handler.lua:202>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:19: in function 'open_dialog'
	__factoryplanner__/ui/main/production_handler.lua:252: in function 'handle_item_click'
	__factoryplanner__/ui/main/production_handler.lua:395: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:165: in function <__factoryplanner__/ui/event_handler.lua:121>
18784.920 Error ServerMultiplayerManager.cpp:84: MultiplayerManager failed: "The mod Factory Planner (2.0.4) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 246)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	[C]: in function '__index'
	__factoryplanner__/ui/base/modal_dialog.lua:174: in function 'enter'
	__factoryplanner__/ui/event_handler.lua:222: in function <__factoryplanner__/ui/event_handler.lua:202>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:19: in function 'open_dialog'
	__factoryplanner__/ui/main/production_handler.lua:252: in function 'handle_item_click'
	__factoryplanner__/ui/main/production_handler.lua:395: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:165: in function <__factoryplanner__/ui/event_handler.lua:121>"

**Comment by ClaudeMetz** [comment] 2024-11-11 23:11
Hi, thanks for the report. This is a duplicate of #219, which I hope to fix very soon.

**Closed by ClaudeMetz** 2024-11-11 23:11 UTC
Labels: bug
