### ISSUE TITLE
UltraCube: crash when clicking on steam ingredient

### ISSUE THREAD

**Issue by pyrachi** [ClaudeMetz/FactoryPlanner#249] opened 2024-01-20 18:53 UTC
### Problem Description

With the UltraCube mod enabled, immediately after clicking on one of the steam ingredients in the GUI to add a recipe, the following crash occurs:

```
The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 282)
__factoryplanner__/backend/data/Machine.lua:62: attempt to index field '?' (a nil value)
stack traceback:
	__factoryplanner__/backend/data/Machine.lua:62: in function 'normalize_fuel'
	__factoryplanner__/backend/data/Line.lua:100: in function 'change_machine_to_proto'
	__factoryplanner__/backend/data/Line.lua:151: in function 'change_machine_to_default'
	__factoryplanner__/ui/dialogs/recipe_dialog.lua:94: in function 'attempt_adding_line'
	__factoryplanner__/ui/dialogs/recipe_dialog.lua:258: in function 'early_abort'
	__factoryplanner__/ui/base/modal_dialog.lua:154: in function 'enter'
	__factoryplanner__/ui/event_handler.lua:209: in function <__factoryplanner__/ui/event_handler.lua:189>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
	__factoryplanner__/ui/main/item_boxes.lua:11: in function 'add_recipe'
	__factoryplanner__/ui/main/item_boxes.lua:161: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
	__factoryplanner__/ui/main/item_boxes.lua:11: in function 'add_recipe'
	__factoryplanner__/ui/main/item_boxes.lua:161: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
```

[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/13998917/factorio-current.log)
[Ultracube.zip](https://github.com/ClaudeMetz/FactoryPlanner/files/13998926/Ultracube.zip)

### Reproduction

1. Load save
2. Open Factory Planner
3. In Factory Planner preferences set the default boiler to the vanilla boiler.
4. Click on steam ingredient in upper right corner.

**Comment by pyrachi** [comment] 2024-01-22 19:11
I cross-posted this to the UltraCube mod.  https://mods.factorio.com/mod/Ultracube/discussion/65ac18503117b0345963cbf6

Per the discussion there, the crash only occurs when the vanilla boiler is selected in the Factory Planner preferences. Switching to UltraCube's boiler eliminates the crash.

**Comment by ClaudeMetz** [comment] 2024-10-13 09:28
Appreciate the detailed report! This is a duplicate of #240, so we'll centralize discussion there.

**Closed by ClaudeMetz** 2024-10-13 09:28 UTC
Labels: bug
