### ISSUE TITLE
Can't load old save

### ISSUE THREAD

**Issue by maxjdobrei** [ClaudeMetz/FactoryPlanner#358] opened 2024-10-22 14:17 UTC
### Problem Description

Tried to load in after updating FactoryPlanner from version 1.1.78 to latest 2.0.1, however it caused a crash. 
Error log:
![image](https://github.com/user-attachments/assets/798f2075-36fa-42f4-9cfe-354de4279aa6)

### Reproduction

1. Start game
2. Load save file with old version of Factory Planner

**Comment by ClaudeMetz** [comment] 2024-10-22 14:43
Hello, thanks for the report. This one has been fixed in the release that just came out, so feel free to give that a go :)

(Dupe of #352)

**Closed by ClaudeMetz** 2024-10-22 14:43 UTC
Labels: bug
