### ISSUE TITLE
Factory Planner sometimes started crashing when opening the window to change the desired item count or configure the machine type

### ISSUE THREAD

**Issue by nicolasalt** [ClaudeMetz/FactoryPlanner#242] opened 2024-01-13 11:14 UTC
### Problem Description

This seem to happen only in multiplayer, specifically when a non-server player does this, but not sure.
This started recently, after the new Factorio update. Current version 1.1.101 build 62011, win64.

Here is the error:
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/1146358/79508c8a-610b-4b6e-a31f-48e179efa4b4)

### Reproduction

1. Start a game in multiplayer (not sure if multiplayer is needed but couldn't reproduce without it).
2. Join the game from another account.
3. Create a new recipe in the planner.
3. Play for a few minutes - sometimes it doesn't crash right after loading.
5. Try changing the desired item count.

**Comment by ClaudeMetz** [comment] 2024-10-13 09:22
Hello, thanks for the report. This is a duplicate of #219, so closing this one :)

**Closed by ClaudeMetz** 2024-10-13 09:22 UTC
Labels: bug
