### ISSUE TITLE
Non-recoverable error when rightclicking beacon

### ISSUE THREAD

**Issue by knoxfighter** [ClaudeMetz/FactoryPlanner#271] opened 2024-02-27 22:03 UTC
### Problem Description

Reliable crash when trying to edit a beacon.

```
The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/ui/main/production_handler.lua:127: attempt to index local 'beacon' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_handler.lua:127: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
```
[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/14426168/factorio-current.log)
[Save](https://drive.google.com/file/d/1tFJXj9Rgw389ND1nqpEfU7FQUJNV86Mb/view?usp=drive_link)

### Reproduction

1. open factorio as user `asdff45`
1. open the provided save
2. open the factory planner
3. rightclick the beacon in the selected Factory (Iron ingot)

### Edit
After i reconnected to the server, the Beacon UI was open and i tried to interact with it. This resulted in a server-crash, similar to #219 
```
207341.366 Error MainLoop.cpp:1404: Exception at tick 51483154: The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event factoryplanner::Custom event (ID 292)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
[C]: in function '__index'
__factoryplanner__/ui/base/modal_dialog.lua:173: in function 'enter'
__factoryplanner__/ui/event_handler.lua:209: in function <__factoryplanner__/ui/event_handler.lua:189>
[C]: in function 'raise_event'
__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
__factoryplanner__/ui/main/production_handler.lua:172: in function 'handler'
__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
[C]: in function 'raise_event'
__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
__factoryplanner__/ui/main/production_handler.lua:172: in function 'handler'
__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
207341.367 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event factoryplanner::Custom event (ID 292)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
[C]: in function '__index'
__factoryplanner__/ui/base/modal_dialog.lua:173: in function 'enter'
__factoryplanner__/ui/event_handler.lua:209: in function <__factoryplanner__/ui/event_handler.lua:189>
[C]: in function 'raise_event'
__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
__factoryplanner__/ui/main/production_handler.lua:172: in function 'handler'
__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
[C]: in function 'raise_event'
__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
__factoryplanner__/ui/main/production_handler.lua:172: in function 'handler'
__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>" 
```

Now i restarted the server and when i click on the beacon, now the server crashes instead of the client:
```
 130.812 Error MainLoop.cpp:1404: Exception at tick 51480754: The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/ui/main/production_handler.lua:127: attempt to index local 'beacon' (a nil value)
stack traceback:
__factoryplanner__/ui/main/production_handler.lua:127: in function 'handler'
__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
130.812 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/ui/main/production_handler.lua:127: attempt to index local 'beacon' (a nil value)
stack traceback:
__factoryplanner__/ui/main/production_handler.lua:127: in function 'handler'
__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>"
```

**Comment by ClaudeMetz** [comment] 2024-10-16 08:14
Thanks for the reports, this is a duplicate of #261, which I fixed for 2.0

**Closed by ClaudeMetz** 2024-10-16 08:14 UTC
Labels: bug
