### ISSUE TITLE
Crash when changing interface height

### ISSUE THREAD

**Issue by heinwessels** [ClaudeMetz/FactoryPlanner#252] opened 2024-01-23 20:28 UTC
### Problem Description

Haven't played this save in a long time, so I updated all my mods. Not really sure if Factory Planner was updated, but now my FP window was too small. It wasn't last time I played, I think. Maybe I played on a different screen. So I was trying to make it bigger.

![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/39875036/2a232786-d9e0-48a4-b331-817a11af1ea1)

I went into preferences,changed the interface height, and clicked on the red x. And crash!

```
1701.401 Error MainLoop.cpp:1391: Exception at tick 8593836: The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 271)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	[C]: in function '__index'
	__factoryplanner__/ui/base/main_dialog.lua:147: in function 'set_pause_state'
	__factoryplanner__/ui/base/main_dialog.lua:109: in function 'rebuild'
	__factoryplanner__/ui/dialogs/preferences_dialog.lua:341: in function 'dialog_close'
	__factoryplanner__/ui/base/modal_dialog.lua:187: in function 'exit'
	__factoryplanner__/ui/event_handler.lua:216: in function <__factoryplanner__/ui/event_handler.lua:189>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:27: in function 'close_dialog'
	__factoryplanner__/ui/base/modal_dialog.lua:285: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:27: in function 'close_dialog'
	__factoryplanner__/ui/base/modal_dialog.lua:285: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
```

---

Thanks for the awesome mod though! For now I will just play with the tiny UI :)

### Reproduction

This is currently consistently reproducable for me using the save file attached and these steps:

1. Open Factory Planner (using `Ctrl-R`)
2. Preferences
3. Set `Interface height` to `22 rows`.
4. Click on `x`
5. Crash!

[Bobs and Angels 2022.zip](https://github.com/ClaudeMetz/FactoryPlanner/files/14029481/Bobs.and.Angels.2022.zip)
[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/14029477/factorio-current.log)

**Comment by ClaudeMetz** [comment] 2024-10-13 09:33
Thanks for the very nice report :) This is a dupe of #224, and it's actually fixed with 2.0 :)

**Closed by ClaudeMetz** 2024-10-13 09:33 UTC
Labels: bug
