### ISSUE TITLE
Factory Planner not allowing the use of productivity modules

### ISSUE THREAD

**Issue by EGBGaming** [ClaudeMetz/FactoryPlanner#253] opened 2024-01-24 16:04 UTC
### Problem Description

When attempting to create a plan for a factory, I am unable to use Productivity modules from the popup menu. Loaded a new save with the same mods and was able to use productivity modules.

Save File is too large to upload here: https://www.dropbox.com/scl/fi/m1klbg0ut6oqnzzbi13ya/fucktoriorun1.zip?rlkey=mndc9dkbfkad1p3u4f0j3kv9o&dl=0

### Reproduction

1. Open Factory Planner
2. Add something like Iron plates as the product and use Electric Furnaces as the source to create them.
3. Add Modules to the machine and you'll find that only speed and efficiency modules can be chosen.

**Comment by EGBGaming** [comment] 2024-01-24 16:15
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/109240049/cb83f7e0-f128-492d-ac53-977d9f7c5e32)

Server just threw this error.

**Comment by EGBGaming** [comment] 2024-01-24 16:29
I attempted to change a parameter in a saved factory layout in the factory planner and server crashed.

**Comment by ClaudeMetz** [comment] 2024-10-13 09:35
Hello, thanks for the reports. The first issue of incompatible modules is hard to diagnose, and seeing as 2.0 is around the corner with changes to this logic, I'd say we wait and see if it comes up again in 2.0.
The crash you got is unrelated, and a duplicate of #168, so I'll be closing this one for now.

**Closed by ClaudeMetz** 2024-10-13 09:35 UTC
Labels: bug
