### ISSUE TITLE
Error while running event factoryplanner::Custom event (ID 210)

### ISSUE THREAD

**Issue by Olipro** [ClaudeMetz/FactoryPlanner#196] opened 2023-11-27 02:53 UTC
### Problem Description

Server crashed due to script error. Sadly not sure what I managed to do wrong, here's the stack trace.

My best guess is that while I was fiddling with the lines, I might have deleted one and there was somehow an orphaned element which could have caused `line.parent` to be `nil`

Error while running event factoryplanner::Custom event (ID 210)
__factoryplanner__/ui/main/production_table.lua:77: attempt to index field 'parent' (a nil value)
stack traceback:
        __factoryplanner__/ui/main/production_table.lua:77: in function '?'
        __factoryplanner__/ui/main/production_table.lua:434: in function 'render_lines'
        __factoryplanner__/ui/main/production_table.lua:438: in function 'render_lines'
        __factoryplanner__/ui/main/production_table.lua:442: in function 'refresh_production_table'
        __factoryplanner__/ui/main/production_table.lua:472: in function 'registered_handler'
        __factoryplanner__/ui/event_handler.lua:308: in function <__factoryplanner__/ui/event_handler.lua:288>
        [C]: in function 'raise_event'
        __factoryplanner__/util/raise.lua:14: in function 'refresh'
        __factoryplanner__/ui/main/production_box.lua:92: in function 'change_floor'
        __factoryplanner__/ui/main/production_box.lua:267: in function 'handler'
        __factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
        [C]: in function 'raise_event'
        __factoryplanner__/util/raise.lua:14: in function 'refresh'
        __factoryplanner__/ui/main/production_box.lua:92: in function 'change_floor'
        __factoryplanner__/ui/main/production_box.lua:267: in function 'handler'
        __factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>"

**Comment by Olipro** [comment] 2023-11-27 03:17
Note: probably a duplicate of #193

**Comment by ClaudeMetz** [comment] 2023-11-27 14:43
Indeed, and by the transitive property of duplication, also a dupe of #182. Appreciate the report nonetheless, but we'll deal with it in 182 going forward.

**Closed by ClaudeMetz** 2023-11-27 14:43 UTC
Labels: bug
