### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Valoneu** [ClaudeMetz/FactoryPlanner#258] opened 2024-02-02 21:52 UTC
### Problem Description

I just changed settings and got this
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/60077591/4655147b-c7a3-4045-b585-92b6a447e2e7)

### Reproduction

changed settings

**Comment by ClaudeMetz** [comment] 2024-10-13 09:43
Hello, duplicate of #224, which is fixed for 2.0

**Closed by ClaudeMetz** 2024-10-13 09:43 UTC
Labels: bug
