### ISSUE TITLE
Non recoverable error

### ISSUE THREAD

**Issue by merlinx2k** [ClaudeMetz/FactoryPlanner#267] opened 2024-02-18 12:24 UTC
### Problem Description

![error](https://github.com/ClaudeMetz/FactoryPlanner/assets/12309631/78833901-7aa6-4029-8fcb-5fa926dc6f2a)

**Comment by ClaudeMetz** [comment] 2024-10-13 18:17
Hello, thanks for the report. This is a dupe of #219, which I'll fix soon.

**Closed by ClaudeMetz** 2024-10-13 18:17 UTC
Labels: bug
