### ISSUE TITLE
Error while Custom event ID 266 attempt to index field 'parent' (a nil value) upon deleting last line of a factory?

### ISSUE THREAD

**Issue by Icicubes** [ClaudeMetz/FactoryPlanner#318] opened 2024-08-07 19:46 UTC
### Problem Description

![20240807203451_1](https://github.com/user-attachments/assets/22266d36-9828-408b-9986-92d392c3c597)

### Reproduction

I didn't manage to reproduce it nor did I find a similar enough open issue. (Factorio 1.1.109)

**Comment by ClaudeMetz** [comment] 2024-10-13 19:13
Seems to be a duplicate of #217, appreciate the report!

**Closed by ClaudeMetz** 2024-10-13 19:13 UTC
Labels: bug
