### ISSUE TITLE
non-recoverable error while hoving over icon in minimized planer

### ISSUE THREAD

**Issue by RockingOrc** [ClaudeMetz/FactoryPlanner#440] opened 2024-12-01 06:09 UTC
### Problem Description

was trying to select multiple icons for constant combinator
------------------
Error while running event factoryplanner::on_gui_hover (ID 189)
__factoryplanner__/ui/base/compact_dialog.lua:540: bad argument #1 of 2 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	__factoryplanner__/ui/base/compact_dialog.lua:540: in function 'handle_hover_change'
	__factoryplanner__/ui/base/compact_dialog.lua:634: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:173: in function <__factoryplanner__/ui/event_handler.lua:121>

### Reproduction

Hover an icon in the small planner windows

**Comment by kirazy** [comment] 2024-12-05 00:51
More examples:
https://github.com/user-attachments/assets/a42f7001-afed-4587-86e0-a7ce33533a3e

With save:
[factory-planner-crash-on-mouse-over.zip](https://github.com/user-attachments/files/18015804/factory-planner-crash-on-mouse-over.zip)

**Comment by ClaudeMetz** [comment] 2024-12-06 14:24
Thanks everyone, this is actually a duplicate of #439, which is fixed for the next release.

**Closed by ClaudeMetz** 2024-12-06 14:24 UTC
Labels: bug
