### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by vfinn** [ClaudeMetz/FactoryPlanner#284] opened 2024-04-05 18:14 UTC
### Problem Description

[factorio-previous (5).log](https://github.com/ClaudeMetz/FactoryPlanner/files/14889259/factorio-previous.5.log)
Log provided

**Comment by ClaudeMetz** [comment] 2024-10-13 18:43
Hello, thanks, dupe of #219 so closing this one

**Closed by ClaudeMetz** 2024-10-13 18:43 UTC
Labels: bug
